### ISSUE TITLE
Static type checker configuration

### ISSUE THREAD

**Issue by ferrine** [caniko/pydantic-numpy#16]
There is an issue to configure pylance properly so it supports typehints

<img width="466" alt="image" src="https://github.com/caniko/pydantic-numpy/assets/11705326/abe68340-1d3f-4a8e-b30b-fef58f89ccc7">

```
from pydantic_numpy.model import NumpyModel
from pydantic_numpy import np_array_pydantic_annotated_typing


class MyModel(NumpyModel):
    input: np_array_pydantic_annotated_typing(dimensions=2)

    def c(self):
        return self.input.size
```

Has anyone solved this issue?

**Comment by ferrine** [comment]
This snippet solves the pylance issue

```
input: np.ndarray = FieldInfo.from_annotated_attribute(
    np_array_pydantic_annotated_typing(dimensions=2), ...
)
```
Could there be a better solution?

**Comment by caniko** [comment]
> Could there be a better solution?

I had an idea that could potentially serve as a bandaid; there is a lack in demand for such feature on the Pydantic side, and I will not pursue it any further.

**Solving the problem**

> input: np.ndarray = FieldInfo.from_annotated_attribute(
>     np_array_pydantic_annotated_typing(dimensions=2), ...

The typing you are providing to `input`, `np.ndarray`, is wrong. `pydantic-numpy` types also accept `FilePath` and `MultiArrayNumpyFile`. The issue seems to be on the Pylance side where it can't determine the type inside annotated types.

You are free to cover this issue on the Pylance repo, and I can join the conversation should you do so! I am closing this issue because it isn't related to the package!

**Comment by caniko** [comment]
This is getting fixed @ferrine
